version: "2.0"

services:
  coolify:
    image: coollabsio/coolify:latest
    env:
      - COOLIFY_DATABASE_URL=file:/data/mydb.sqlite
      - COOLIFY_SECRET_KEY=
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    resources:
      cpu:
        units: 2.0  
      memory:
        size: 3Gi  
      storage:
        size: 50Gi 

profiles:
  compute:
    coolify:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 2Gi
        storage:
          size: 30Gi
  placement:
    westcoast:
      pricing:
        coolify:
          denom: uakt
          amount: 1000  

deployment:
  coolify:
    westcoast:
      profile: coolify
      count: 1
